# Generated by Django 5.2.3 on 2025-11-20 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='catalog.language')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='catalog.location')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
                'indexes': [models.Index(fields=['release_date'], name='catalog_mov_release_388f45_idx'), models.Index(fields=['language'], name='catalog_mov_languag_aacee0_idx'), models.Index(fields=['location'], name='catalog_mov_locatio_abc978_idx')],
            },
        ),
    ]
