# Generated by Django 5.2.3 on 2025-11-21 15:00

import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/', validators=[uploader.models.validate_file_size])),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/docs/', validators=[uploader.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
